# Generated by Django 5.0.4 on 2024-09-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
