# Generated by Django 5.0.7 on 2024-10-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='foto_cadastro',
            field=models.ImageField(null=True, upload_to='Foto_cadastro'),
        ),
    ]
