# Generated by Django 5.0.7 on 2025-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_user_doc_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_pix',
            field=models.CharField(choices=[('', 'Selecione uma opção'), ('tel', 'Telefone'), ('mai', 'Email'), ('doc', 'Documento')], max_length=3, null=True),
        ),
    ]
