# Generated by Django 5.0.7 on 2026-08-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_mensagemcontato'),
        ('website', '0008_user_tipo_pix'),
    ]

    operations = [
    ]
