# Generated by Django 5.0.7 on 2026-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_merge_0008_mensagemcontato_0008_user_tipo_pix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tipo_pix',
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
