server {
    listen 80;
    server_name pscservice.site www.pscservice.site;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    # Substitua pelo caminho real de seus arquivos estáticos
    location /static/ {
        alias /var/www/sige_psc/staticfiles/;
    }

    location / {
        include proxy_params;
        # Substitua pelo caminho real do arquivo .sock do projeto
        proxy_pass http://unix:/var/www/sige_psc/sige_psc.sock;
    }
}
